service: smart-clean-api

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  stage: production
  region: ap-southeast-1

functions:
  authorise:
    handler: services/auth/handler.isUserAuthorised

  register:
    handler: services/auth/handler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  login: 
    handler: services/auth/handler.login
    events:
      - http:
          path: login
          method: post
          cors: true


plugins:
  - serverless-offline